spring.application.name=tire-testing


# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/tire_testing_db
spring.datasource.username=tire_user
spring.datasource.password=Raiyanhasan4949

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Fix driver issue explicitly
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=mysecretkey
jwt.expiration=3600000